{% set name = "conda-project" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda-incubator/conda-project/archive/refs/tags/{{ version }}.tar.gz
  sha256: 77d541ddd7b4d532d97673a811b0e5fbc95083d1477456c3057d46021a124fb5

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - conda-project = conda_project.cli.main:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools <=65.0.0
  run:
    - python >=3.8
    - conda-lock >=1.2
    - lockfile
    - pexpect
    - ruamel.yaml
    - pydantic
    - shellingham
    - python-dotenv

test:
  imports:
    - conda_project
  commands:
    - conda-project --help

about:
  home: https://github.com/conda-incubator/conda-project
  summary: 'Tool for encapsulating, running, and reproducing projects with conda environments'
  description: |
    Sharing your work is more than sharing your code in a script file or notebook. To make your
    work properly reproducible, it is necessary to include the list of required third-party
    dependencies, specifications for how to run your code, and any other files that it may need.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://conda-incubator.github.io/conda-project/user_guide.html
  dev_url: https://github.com/conda-incubator/conda-project

extra:
  recipe-maintainers:
    - AlbertDeFusco
    - mattkram
